//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OES_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int ExamId { get; set; }
        public int UserId { get; set; }
        public int TechId { get; set; }
        public int LevelId { get; set; }
        public int Score { get; set; }
        public bool Status { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
    }
}
